export const FETCH_MOVIES_BEGIN = 'FETCH_MOVIES_BEGIN'
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR'

export const FETCH_GENRES = 'FETCH_GENRES'
export const FETCH_GENRES_ERROR = 'FETCH_GENRES_ERROR'

export const SELECT_SORT = 'SELECT_SORT'
export const SELECT_GENRES = 'SELECT_GENRES'
